name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Type of release: patch, minor, major"
        required: true
        default: patch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout репозитория с PAT
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      # 2. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. Установка зависимостей
      - name: Install dependencies
        run: npm ci

      # 4. Установка git identity
      - name: Set Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 5. Подготовка CHANGELOG.md (если нет)
      - name: Ensure CHANGELOG.md exists
        run: |
          if [ ! -f CHANGELOG.md ]; then
            echo "# Changelog" > CHANGELOG.md
            git add CHANGELOG.md
            git commit -m "chore: add initial CHANGELOG.md"
            git push origin dev
          fi

      # 6. Создание релиза с standard-version
      - name: Create Release
        run: |
          git checkout dev
          git pull origin dev

          # Генерация версии и CHANGELOG
          npx standard-version --release-as ${{ github.event.inputs.release_type }}

          # Пушим коммиты и тег в dev
          git push origin dev --follow-tags

          # Получаем последний тег
          NEW_TAG=$(git describe --tags --abbrev=0)
          echo "New release tag: $NEW_TAG"

          # Мержим изменения в main
          git checkout main
          git pull origin main
          git merge --no-ff dev -m "chore(release): merge release $NEW_TAG from dev"
          git push origin main --follow-tags

      # 7. Создание GitHub Release через CLI
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          NEW_TAG=$(git describe --tags --abbrev=0)
          echo "Creating GitHub Release $NEW_TAG"
          gh release create $NEW_TAG -t "Release $NEW_TAG" -n "Автоматический релиз из dev"

      # 8. Обновление README с последним changelog (опционально)
      - name: Update README with latest changelog
        run: |
          NEW_TAG=$(git describe --tags --abbrev=0)
          LATEST_LOG=$(awk '/^## \[/{print; exit}' CHANGELOG.md)
          sed -i "s/LATEST_RELEASE_PLACEHOLDER/${LATEST_LOG}/" README.md || true
          git add README.md
          git commit -m "chore: update README with latest changelog $NEW_TAG" || true
          git push origin main
